### ISSUE TITLE
Improve accessibility and UI in Our activities page

### ISSUE THREAD

**Issue by SanjayDevTech** [KISHOREMUTHU/ETE2---Sparky#2]

**Comment by KISHOREMUTHU** [comment]
Yes , we can work on it Sanjay . Give me your e-mail . I will make you as a collaborator . Then , you start working on the UI enhancements and ask for further instructions

**Comment by SanjayDevTech** [comment]
@KISHOREMUTHU sure here is mine: sureshsanjay805@gmail.com

And please add LGMSOC21 label to make this issue eligible for LGMSOC

**Comment by Priyanshu078** [comment]
Hi this is Priyanshu Paliwal LGM SOC participant and please assign me this issue

**Comment by Priyanshu078** [comment]
priyanshupaliwal078@gmail.com

**Comment by SanjayDevTech** [comment]
I'm closing this issue
