### ISSUE TITLE
Add Contribution Guidelines in Readme File

### ISSUE THREAD

**Issue by Shaishav0507** [KISHOREMUTHU/ETE2---Sparky#8]
Hey @KISHOREMUTHU @arq0017 
I would like to add contribution guidelines to the readme file.
Please assign it to me.
Thanks.

**Comment by Shaishav0507** [comment]
@KISHOREMUTHU Can I go ahead?

**Comment by KISHOREMUTHU** [comment]
Ok sure , Shaishav .Just download the Readme file and start working on it

**Comment by Shaishav0507** [comment]
Ok
Assign me on the issue.

**Comment by Ayan-thecodeking** [comment]
hey @KISHOREMUTHU i want to add contribution guidelines in readme 
please assign me for this ..
if issue is open 
thanks :)

**Comment by KISHOREMUTHU** [comment]
Sure @Ayan-thecodeking  . Please provide me a readme.md on this , and I will attach that
